# Documentation: http://docs.travis-ci.com/user/languages/julia
language: julia
notifications:
  email: false
julia:
  - 1.2
  - 1.3
  - nightly
os:
  - linux
  - osx
  - windows
arch:
  - x64
jobs:
  fast_finish: true
  allow_failures:
    - julia: nightly
