# Documentation: http://docs.travis-ci.com/user/languages/julia
language: julia
notifications:
  email: false
julia:
  - 1.2
  - 1.3
  - nightly
os:
  - linux
  - osx
  - windows
arch:
  - x64
after_success:
  # push coverage results to Coveralls
  - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

jobs:
  fast_finish: true
  allow_failures:
    - julia: nightly
